modLoader = "javafml"
loaderVersion = "[4,)"
license = "Unlicense"

[[mods]]
modId = "frozenregfixtest"
version = "1"
displayName = "Frozen Registry Fix client tests"
description = "Test-only assertions for Frozen Registry Fix"

[[dependencies.frozenregfixtest]]
modId = "frozenregfix"
type = "required"
versionRange = "[2,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.frozenregfixtest]]
modId = "immersive_armors"
type = "required"
versionRange = "[1.7,)"
ordering = "AFTER"
side = "CLIENT"
